Modified CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,84 +28,84 @@ jobs:
       - name: Run Unit Tests
         run: pytest -v
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: "1.5.7"
+      # - name: Setup Terraform
+      #   uses: hashicorp/setup-terraform@v2
+      #   with:
+      #     terraform_version: "1.5.7"
 
-      - name: Terraform Format Check
-        run: terraform fmt -check
-        working-directory: ./terraform
+  #     - name: Terraform Format Check
+  #       run: terraform fmt -check
+  #       working-directory: ./terraform
 
-      - name: Terraform Init
-        run: terraform init -backend=false
-        working-directory: ./terraform
+  #     - name: Terraform Init
+  #       run: terraform init -backend=false
+  #       working-directory: ./terraform
 
-      - name: Terraform Validate
-        run: terraform validate
-        working-directory: ./terraform
+  #     - name: Terraform Validate
+  #       run: terraform validate
+  #       working-directory: ./terraform
 
-  terraform-plan:
-    name: Terraform Plan
-    needs: test-and-validate
-    if: github.event_name == 'pull_request'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+  # terraform-plan:
+  #   name: Terraform Plan
+  #   needs: test-and-validate
+  #   if: github.event_name == 'pull_request'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v3
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: "1.5.7"
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: "1.5.7"
 
-      - name: Setup AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ap-southeast-1
+  #     - name: Setup AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ap-southeast-1
 
-      - name: Terraform Init
-        run: terraform init
-        working-directory: ./terraform
+  #     - name: Terraform Init
+  #       run: terraform init
+  #       working-directory: ./terraform
 
-      - name: Terraform Plan
-        run: terraform plan
-        working-directory: ./terraform
+  #     - name: Terraform Plan
+  #       run: terraform plan
+  #       working-directory: ./terraform
 
-  terraform-apply:
-    name: Terraform Apply (Manual only)
-    needs: test-and-validate
-    if: github.event_name == 'workflow_dispatch'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+  # terraform-apply:
+  #   name: Terraform Apply (Manual only)
+  #   needs: test-and-validate
+  #   if: github.event_name == 'workflow_dispatch'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v3
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: "1.5.7"
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: "1.5.7"
 
-      - name: Setup AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ap-southeast-1
+  #     - name: Setup AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ap-southeast-1
 
-      - name: Terraform Init
-        run: terraform init
-        working-directory: ./terraform
+  #     - name: Terraform Init
+  #       run: terraform init
+  #       working-directory: ./terraform
 
-      - name: Terraform Apply
-        run: terraform apply -auto-approve
-        working-directory: ./terraform
+  #     - name: Terraform Apply
+  #       run: terraform apply -auto-approve
+  #       working-directory: ./terraform
 
-      - name: Post-Deployment Smoke Test
-        run: |
-          API_URL=$(terraform output -raw api_v1_endpoint)
-          echo "API URL is $API_URL"
-          curl -f -s "${API_URL}products" || (echo "Smoke test failed!" && exit 1)
-        working-directory: ./terraform
+  #     - name: Post-Deployment Smoke Test
+  #       run: |
+  #         API_URL=$(terraform output -raw api_v1_endpoint)
+  #         echo "API URL is $API_URL"
+  #         curl -f -s "${API_URL}products" || (echo "Smoke test failed!" && exit 1)
+  #       working-directory: ./terraform
